pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["afiarea_blocurilor_textuale_al.htm","Afișarea blocurilor textuale ale documentului","Afișarea blocurilor textuale ale documentului Top Previous Next În CKEditor diverse acțiuni pot fi aplicate doar unor blocuri predefinite de eleme...",""],
["alegerea_caracterelor.htm","Alegerea caracterelor","Alegerea caracterelor Top Previous Next În CKEditor Caracterele (Fontul) reprezintă aspectul vizual al textului plasat pe site sau în document. Ca...",""],
["alinierea_textului.htm","Alinierea textului","Alinierea textului Top Previous Next Alinierea determină modalitatea de plasare a textului în pagină. În acest sens, alinierea se execută pe fieca...",""],
["alte_comenzi.htm","Alte comenzi","Alte comenzi Top Previous Next CTRL+L – deschide fereastra de dialog Link ALT+0 – deschide fereastra de ajutor ALT+- (minus) – închide și deschide...",""],
["anexa_nr_1.htm","Anexa Nr.1","Anexa Nr.1 Top Previous Next 1. CETĂȚENI ȘI BUSINESS 1.1. Beneficii sociale și ajutoare 1.1.1. Ajutoare sociale familiale 1.1.2. Bursa muncii / Aj...",""],
["anexa_nr_10.htm","Anexa Nr.10","Anexa Nr.10 Top Previous Next ",""],
["anexa_nr_100.htm","Anexa Nr.100","Anexa Nr.100 Top Previous Next ",""],
["anexa_nr_101.htm","Anexa Nr.101","Anexa Nr.101 Top Previous Next ",""],
["anexa_nr_102.htm","Anexa Nr.102","Anexa Nr.102 Top Previous Next ",""],
["anexa_nr_103.htm","Anexa Nr.103","Anexa Nr.103 Top Previous Next ",""],
["anexa_nr_104.htm","Anexa Nr.104","Anexa Nr.104 Top Previous Next ",""],
["anexa_nr_105.htm","Anexa Nr.105","Anexa Nr.105 Top Previous Next ",""],
["anexa_nr_106.htm","Anexa Nr.106","Anexa Nr.106 Top Previous Next ",""],
["anexa_nr_107.htm","Anexa Nr.107","Anexa Nr.107 Top Previous Next ",""],
["anexa_nr_108.htm","Anexa Nr.108","Anexa Nr.108 Top Previous Next ",""],
["anexa_nr_109.htm","Anexa Nr.109","Anexa Nr.109 Top Previous Next ",""],
["anexa_nr_11.htm","Anexa Nr.11","Anexa Nr.11 Top Previous Next ",""],
["anexa_nr_110.htm","Anexa Nr.110","Anexa Nr.110 Top Previous Next ",""],
["anexa_nr_111.htm","Anexa Nr.111","Anexa Nr.111 Top Previous Next ",""],
["anexa_nr_112.htm","Anexa Nr.112","Anexa Nr.112 Top Previous Next ",""],
["anexa_nr_113.htm","Anexa Nr.113","Anexa Nr.113 Top Previous Next ",""],
["anexa_nr_114.htm","Anexa Nr.114","Anexa Nr.114 Top Previous Next ",""],
["anexa_nr_115.htm","Anexa Nr.115","Anexa Nr.115 Top Previous Next ",""],
["anexa_nr_116.htm","Anexa Nr.116","Anexa Nr.116 Top Previous Next ",""],
["anexa_nr_117.htm","Anexa Nr.117","Anexa Nr.117 Top Previous Next ",""],
["anexa_nr_118.htm","Anexa Nr.118","Anexa Nr.118 Top Previous Next Enter topic text here. ",""],
["anexa_nr_119.htm","Anexa Nr.119","Anexa Nr.119 Top Previous Next ",""],
["anexa_nr_12.htm","Anexa Nr.12","Anexa Nr.12 Top Previous Next ",""],
["anexa_nr_120.htm","Anexa Nr.120","Anexa Nr.120 Top Previous Next ",""],
["anexa_nr_121.htm","Anexa Nr.121","Anexa Nr.121 Top Previous Next ",""],
["anexa_nr_122.htm","Anexa Nr.122","Anexa Nr.122 Top Previous Next ",""],
["anexa_nr_123.htm","Anexa Nr.123","Anexa Nr.123 Top Previous Next ",""],
["anexa_nr_124.htm","Anexa Nr.124","Anexa Nr.124 Top Previous Next ",""],
["anexa_nr_125.htm","Anexa Nr.125","Anexa Nr.125 Top Previous Next ",""],
["anexa_nr_126.htm","Anexa Nr.126","Anexa Nr.126 Top Previous Next ",""],
["anexa_nr_127.htm","Anexa Nr.127","Anexa Nr.127 Top Previous Next ",""],
["anexa_nr_128.htm","Anexa Nr.128","Anexa Nr.128 Top Previous ",""],
["anexa_nr_13.htm","Anexa Nr.13","Anexa Nr.13 Top Previous Next ",""],
["anexa_nr_14.htm","Anexa Nr.14","Anexa Nr.14 Top Previous Next ",""],
["anexa_nr_15.htm","Anexa Nr.15","Anexa Nr.15 Top Previous Next ",""],
["anexa_nr_16.htm","Anexa Nr.16","Anexa Nr.16 Top Previous Next ",""],
["anexa_nr_17.htm","Anexa Nr.17","Anexa Nr.17 Top Previous Next ",""],
["anexa_nr_18.htm","Anexa Nr.18","Anexa Nr.18 Top Previous Next ",""],
["anexa_nr_19.htm","Anexa Nr.19","Anexa Nr.19 Top Previous Next ",""],
["anexa_nr_2.htm","Anexa Nr.2","Anexa Nr.2 Top Previous Next ",""],
["anexa_nr_20.htm","Anexa Nr.20","Anexa Nr.20 Top Previous Next ",""],
["anexa_nr_21.htm","Anexa Nr.21","Anexa Nr.21 Top Previous Next ",""],
["anexa_nr_22.htm","Anexa Nr.22","Anexa Nr.22 Top Previous Next ",""],
["anexa_nr_23.htm","Anexa Nr.23","Anexa Nr.23 Top Previous Next ",""],
["anexa_nr_24.htm","Anexa Nr.24","Anexa Nr.24 Top Previous Next ",""],
["anexa_nr_25.htm","Anexa Nr.25","Anexa Nr.25 Top Previous Next ",""],
["anexa_nr_26.htm","Anexa Nr.26","Anexa Nr.26 Top Previous Next ",""],
["anexa_nr_27.htm","Anexa Nr.27","Anexa Nr.27 Top Previous Next ",""],
["anexa_nr_28.htm","Anexa Nr.28","Anexa Nr.28 Top Previous Next ",""],
["anexa_nr_29.htm","Anexa Nr.29","Anexa Nr.29 Top Previous Next ",""],
["anexa_nr_3.htm","Anexa Nr.3","Anexa Nr.3 Top Previous Next ",""],
["anexa_nr_30.htm","Anexa Nr.30","Anexa Nr.30 Top Previous Next ",""],
["anexa_nr_31.htm","Anexa Nr.31","Anexa Nr.31 Top Previous Next ",""],
["anexa_nr_32.htm","Anexa Nr.32","Anexa Nr.32 Top Previous Next ",""],
["anexa_nr_33.htm","Anexa Nr.33","Anexa Nr.33 Top Previous Next Enter topic text here. ",""],
["anexa_nr_34.htm","Anexa Nr.34","Anexa Nr.34 Top Previous Next ",""],
["anexa_nr_35.htm","Anexa Nr.35","Anexa Nr.35 Top Previous Next ",""],
["anexa_nr_36.htm","Anexa Nr.36","Anexa Nr.36 Top Previous Next ",""],
["anexa_nr_37.htm","Anexa Nr.37","Anexa Nr.37 Top Previous Next ",""],
["anexa_nr_38.htm","Anexa Nr.38","Anexa Nr.38 Top Previous Next ",""],
["anexa_nr_39.htm","Anexa Nr.39","Anexa Nr.39 Top Previous Next ",""],
["anexa_nr_4.htm","Anexa Nr.4","Anexa Nr.4 Top Previous Next ",""],
["anexa_nr_40.htm","Anexa Nr.40","Anexa Nr.40 Top Previous Next ",""],
["anexa_nr_41.htm","Anexa Nr.41","Anexa Nr.41 Top Previous Next ",""],
["anexa_nr_42.htm","Anexa Nr.42","Anexa Nr.42 Top Previous Next ",""],
["anexa_nr_43.htm","Anexa Nr.43","Anexa Nr.43 Top Previous Next ",""],
["anexa_nr_44.htm","Anexa Nr.44","Anexa Nr.44 Top Previous Next ",""],
["anexa_nr_45.htm","Anexa Nr.45","Anexa Nr.45 Top Previous Next ",""],
["anexa_nr_46.htm","Anexa Nr.46","Anexa Nr.46 Top Previous Next ",""],
["anexa_nr_47.htm","Anexa Nr.47","Anexa Nr.47 Top Previous Next ",""],
["anexa_nr_48.htm","Anexa Nr.48","Anexa Nr.48 Top Previous Next ",""],
["anexa_nr_49.htm","Anexa Nr.49","Anexa Nr.49 Top Previous Next ",""],
["anexa_nr_5.htm","Anexa Nr.5","Anexa Nr.5 Top Previous Next ",""],
["anexa_nr_50.htm","Anexa Nr.50","Anexa Nr.50 Top Previous Next Enter topic text here. ",""],
["anexa_nr_51.htm","Anexa Nr.51","Anexa Nr.51 Top Previous Next ",""],
["anexa_nr_52.htm","Anexa Nr.52","Anexa Nr.52 Top Previous Next ",""],
["anexa_nr_53.htm","Anexa Nr.53","Anexa Nr.53 Top Previous Next Enter topic text here. ",""],
["anexa_nr_54.htm","Anexa Nr.54","Anexa Nr.54 Top Previous Next ",""],
["anexa_nr_55.htm","Anexa Nr.55","Anexa Nr.55 Top Previous Next ",""],
["anexa_nr_56.htm","Anexa Nr.56","Anexa Nr.56 Top Previous Next ",""],
["anexa_nr_57.htm","Anexa Nr.57","Anexa Nr.57 Top Previous Next ",""],
["anexa_nr_58.htm","Anexa Nr.58","Anexa Nr.58 Top Previous Next Enter topic text here. ",""],
["anexa_nr_59.htm","Anexa Nr.59","Anexa Nr.59 Top Previous Next ",""],
["anexa_nr_6.htm","Anexa Nr.6","Anexa Nr.6 Top Previous Next ",""],
["anexa_nr_60.htm","Anexa Nr.60","Anexa Nr.60 Top Previous Next ",""],
["anexa_nr_61.htm","Anexa Nr.61","Anexa Nr.61 Top Previous Next ",""],
["anexa_nr_62.htm","Anexa Nr.62","Anexa Nr.62 Top Previous Next ",""],
["anexa_nr_63.htm","Anexa Nr.63","Anexa Nr.63 Top Previous Next ",""],
["anexa_nr_64.htm","Anexa Nr.64","Anexa Nr.64 Top Previous Next ",""],
["anexa_nr_65.htm","Anexa Nr.65","Anexa Nr.65 Top Previous Next ",""],
["anexa_nr_66.htm","Anexa Nr.66","Anexa Nr.66 Top Previous Next ",""],
["anexa_nr_67.htm","Anexa Nr.67","Anexa Nr.67 Top Previous Next ",""],
["anexa_nr_68.htm","Anexa Nr.68","Anexa Nr.68 Top Previous Next ",""],
["anexa_nr_69.htm","Anexa Nr.69","Anexa Nr.69 Top Previous Next ",""],
["anexa_nr_7.htm","Anexa Nr.7","Anexa Nr.7 Top Previous Next ",""],
["anexa_nr_70.htm","Anexa Nr.70","Anexa Nr.70 Top Previous Next ",""],
["anexa_nr_71.htm","Anexa Nr.71","Anexa Nr.71 Top Previous Next ",""],
["anexa_nr_72.htm","Anexa Nr.72","Anexa Nr.72 Top Previous Next ",""],
["anexa_nr_73.htm","Anexa Nr.73","Anexa Nr.73 Top Previous Next ",""],
["anexa_nr_74.htm","Anexa Nr.74","Anexa Nr.74 Top Previous Next ",""],
["anexa_nr_75.htm","Anexa Nr.75","Anexa Nr.75 Top Previous Next ",""],
["anexa_nr_76.htm","Anexa Nr.76","Anexa Nr.76 Top Previous Next ",""],
["anexa_nr_77.htm","Anexa Nr.77","Anexa Nr.77 Top Previous Next ",""],
["anexa_nr_78.htm","Anexa Nr.78","Anexa Nr.78 Top Previous Next ",""],
["anexa_nr_79.htm","Anexa Nr.79","Anexa Nr.79 Top Previous Next ",""],
["anexa_nr_8.htm","Anexa Nr.8","Anexa Nr.8 Top Previous Next ",""],
["anexa_nr_80.htm","Anexa Nr.80","Anexa Nr.80 Top Previous Next ",""],
["anexa_nr_81.htm","Anexa Nr.81","Anexa Nr.81 Top Previous Next ",""],
["anexa_nr_82.htm","Anexa Nr.82","Anexa Nr.82 Top Previous Next ",""],
["anexa_nr_83.htm","Anexa Nr.83","Anexa Nr.83 Top Previous Next ",""],
["anexa_nr_84.htm","Anexa Nr.84","Anexa Nr.84 Top Previous Next ",""],
["anexa_nr_85.htm","Anexa Nr.85","Anexa Nr.85 Top Previous Next ",""],
["anexa_nr_86.htm","Anexa Nr.86","Anexa Nr.86 Top Previous Next ",""],
["anexa_nr_87.htm","Anexa Nr.87","Anexa Nr.87 Top Previous Next ",""],
["anexa_nr_88.htm","Anexa Nr.88","Anexa Nr.88 Top Previous Next ",""],
["anexa_nr_89.htm","Anexa Nr.89","Anexa Nr.89 Top Previous Next ",""],
["anexa_nr_9.htm","Anexa Nr.9","Anexa Nr.9 Top Previous Next ",""],
["anexa_nr_90.htm","Anexa Nr.90","Anexa Nr.90 Top Previous Next ",""],
["anexa_nr_91.htm","Anexa Nr.91","Anexa Nr.91 Top Previous Next ",""],
["anexa_nr_92.htm","Anexa Nr.92","Anexa Nr.92 Top Previous Next ",""],
["anexa_nr_93.htm","Anexa Nr.93","Anexa Nr.93 Top Previous Next ",""],
["anexa_nr_94.htm","Anexa Nr.94","Anexa Nr.94 Top Previous Next ",""],
["anexa_nr_95.htm","Anexa Nr.95","Anexa Nr.95 Top Previous Next ",""],
["anexa_nr_96.htm","Anexa Nr.96","Anexa Nr.96 Top Previous Next ",""],
["anexa_nr_97.htm","Anexa Nr.97","Anexa Nr.97 Top Previous Next ",""],
["anexa_nr_98.htm","Anexa Nr.98","Anexa Nr.98 Top Previous Next ",""],
["anexa_nr_99.htm","Anexa Nr.99","Anexa Nr.99 Top Previous Next ",""],
["anexe.htm","ANEXE","ANEXE Top Previous Next Enter topic text here. ",""],
["anulare_i_refacere.htm","Anulare și refacere","Anulare și refacere Top Previous Next Butoanele Anulare și Refacere din CKEditor permite o editare textuală și prin reținerea acțiunilor cronologi...",""],
["anulare__refacere.htm","Anulare &#38; Refacere","Anulare &#38; Refacere Top Previous Next CTRL+Z – echivalentul la UNDO CTRL+Y – echivalentul la REDO ",""],
["aranjarea_in_pagin_a_textului.htm","Aranjarea în pagină a textului","Aranjarea în pagină a textului Top Previous Next Aranjarea în pagină a textului (Text Layout) determină structura acestuia. În acest sens, opțiuni...",""],
["atribuirea_de_culori_fundalulu.htm","Atribuirea de culori fundalului textului","Atribuirea de culori fundalului textului Top Previous Next CKEditorul permite a atribui culori fundalului textului introdus pe site. Similar fontu...",""],
["atribuirea_de_culori_textului.htm","Atribuirea de culori textului","Atribuirea de culori textului Top Previous Next CKEditorul permite a atribui culori textului introdus pe site. Similar fonturilor, aceste opțiuni ...",""],
["bold__italic__subliniere_i_tie.htm","Bold, italic, subliniere și tăiere","Bold, italic, subliniere și tăiere Top Previous Next Aceste 4 opțiuni atribuite caracterelor sunt cele mai des utilizate atât pentru documentele o...",""],
["caut_i_inlocuiete.htm","Caută și înlocuiește","Caută și înlocuiește Top Previous Next Opțiunile de căutare și înlocuire sunt utilizate pentru a găsi în zona textuală textul dorit și a executa d...",""],
["ckeditor__prezentare_general.htm","CKEditor – Prezentare generală","CKEditor – Prezentare generală Top Previous Next CKEditor este un editor online de text, care pot fi încorporate în interiorul pagini web. Este un...",""],
["comenzile_rapide_de_la_tastatu.htm","Comenzile rapide de la tastatură","Comenzile rapide de la tastatură Top Previous Next Multe funcții în CKEditor au comenzi echivalente rapide de la tastatură. Acesta este unul dintr...",""],
["comisii.htm","Comisii","Comisii Top Previous Next Comisiile se bazează preponderent pe Consilier, iar de aici și a apărut necesitatea ca o persoană să poată fi atribuită ...",""],
["concluzii.htm","Concluzii","Concluzii Top Previous Next Prezentul manual de utilizare este elaborat pentru versiunea inițială și actuală a platformei WebAPL 1.0. Manualul exp...",""],
["consilieri.htm","Consilieri","Consilieri Top Previous Next Dacă Primarul, viceprimarul și secretarul consiliului se prezintă a fi informații ceva mai detaliate și prezentate în...",""],
["crearea_listelor.htm","Crearea listelor","Crearea listelor Top Previous Next Listele reprezintă textul într-o manieră clară și oferă oportunitatea de a le grupa împreună. CKEditorul permit...",""],
["crearea_noutilor_i_alertelor.htm","Crearea noutăților și alertelor","Crearea noutăților și alertelor Top Previous Next Paginile de noutăți probabil sunt cele mai frecvente pagini ce vor fi actualizate pe site-ul APL...",""],
["crearea_paginii_pentru_petiii_.htm","Crearea paginii pentru petiții on-line și gestiunea lor","Crearea paginii pentru petiții on-line și gestiunea lor Top Previous Next Pe lângă instrumentele indicate, platforma WebAPL permite de a recepțion...",""],
["crearea_paginii_tip_bloc.htm","Crearea paginii tip bloc","Crearea paginii tip bloc Top Previous Next Pagina tip bloc este o pagină care nu posedă un conținut textual, însă cuprinde în sine cel puțin 2 pag...",""],
["crearea_paginilor_anunuri_i_al.htm","Crearea paginilor anunțuri și alerte","Crearea paginilor anunțuri și alerte Top Previous Next Paginile de noutăți probabil sunt cele mai frecvente pagini ce vor fi actualizate pe site-u...",""],
["crearea_paginilor_cadrul_legal.htm","Crearea paginilor cadrul legal APL sau linkuri externe","Crearea paginilor cadrul legal APL sau linkuri externe Top Previous Next Paginile de tip cadrul legal al APL cuprind un design specific dat de inf...",""],
["crearea_paginilor_calendar_i_p.htm","Crearea paginilor calendar și plasarea evenimentelor în calendar","Crearea paginilor calendar și plasarea evenimentelor în calendar Top Previous Next Platforma WebAPL este o platformă cu diverse instrumente ce pot...",""],
["crearea_paginilor_cu_documente.htm","Crearea paginilor cu documente grupate în dosare (mape)","Crearea paginilor cu documente grupate în dosare (mape) Top Previous Next Paginile de tip Regulamente sau pagini cu Documente pe ele grupate în ma...",""],
["crearea_paginilor_cu_formularu.htm","Crearea paginilor cu formularul pentru înscriere la audiență","Crearea paginilor cu formularul pentru înscriere la audiență Top Previous Next Paginile care susțin formularul pentru o înregistrare la audiență p...",""],
["crearea_paginilor_cu_materiale.htm","Crearea paginilor cu materiale video și înregistrări on-line","Crearea paginilor cu materiale video și înregistrări on-line Top Previous Next Pe lângă pagini textuale platforma permite a crea pagini care conți...",""],
["crearea_paginilor_lista_primri.htm","Crearea paginilor lista primării (orașe)","Crearea paginilor lista primării (orașe) Top Previous Next Paginile lista primării (orașe) sunt pagini care sunt orientate pe indicarea comunități...",""],
["crearea_paginilor_ordinea_de_z.htm","Crearea paginilor ordinea de zi și ședințe anterioare","Crearea paginilor ordinea de zi și ședințe anterioare Top Previous Next Paginile tipice ordinea de zi se referă la pagini care au drept scop a fi ...",""],
["crearea_paginilor_simple_ca_li.htm","Crearea paginilor simple ca listă de articole","Crearea paginilor simple ca listă de articole Top Previous Next Desigur că odată funcțional site-ul APL probabil că va putea să posede și alte tip...",""],
["crearea_paginilor_tip_autoriza.htm","Crearea paginilor tip autorizații (ca tabel)","Crearea paginilor tip autorizații (ca tabel) Top Previous Next De la un tip de tabel vom trece la alte tipuri. În cazul în care construirea de tab...",""],
["crearea_paginilor_tip_lista_de.htm","Crearea paginilor tip lista de întrebări / răspunsuri (FAQ)","Crearea paginilor tip lista de întrebări / răspunsuri (FAQ) Top Previous Next Paginile de tip Lista de întrebări / răspunsuri (FAQ) sunt pagini ti...",""],
["crearea_proiectelor.htm","Crearea proiectelor","Crearea proiectelor Top Previous Next Paginile tip lista de proiecte sunt pagini specifice care implică o afișare mai puțin standardă a informații...",""],
["crearea_sondajelor_i_vizualiza.htm","Crearea sondajelor și vizualizarea rezultatelor","Crearea sondajelor și vizualizarea rezultatelor Top Previous Next Platforma WebAPL 1.0. prevede la etapa actuală crearea de sondaje de un singur t...",""],
["crearea_tabelelor.htm","Crearea tabelelor","Crearea tabelelor Top Previous Next Pentru a crea un tabel în CKEditor, apăsați butonul din bara de instrumente. Fereastra de dialog Proprietățile...",""],
["crearea_textelor_formatate.htm","Crearea textelor formatate","Crearea textelor formatate Top Previous Next Această secțiune descrie unele caracteristici ale CKEditor care vă permit să creați conținut cu adevă...",""],
["crearea_unei_linii_orizontale.htm","Crearea unei linii orizontale","Crearea unei linii orizontale Top Previous Next Linia orizontală este un separator care divide / taie pagina în 2 părți ale aceluiași document, fă...",""],
["crearea_unei_pagini_consultri_.htm","Crearea unei pagini consultări curente","Crearea unei pagini consultări curente Top Previous Next Dacă paginile de achiziții se aseamănă cu noutățile și anunțurile, atunci pagina cu tip d...",""],
["crearea_unei_pagini_cu_fiiere.htm","Crearea unei pagini cu fișiere","Crearea unei pagini cu fișiere Top Previous Next Pagina cu fișiere este o pagină care este orientată spre plasarea unor modele de documente ce se ...",""],
["crearea_unei_pagini_i_postarea.htm","Crearea unei pagini și postarea unui post vacant","Crearea unei pagini și postarea unui post vacant Top Previous Next Anunțurile cu privire la posturile vacante plasate pe site-ul APL se vor putea ...",""],
["crearea_unei_pagini_lista_de_l.htm","Crearea unei pagini lista de locații (cultură) și locațiilor aferente acesteia","Crearea unei pagini lista de locații (cultură) și locațiilor aferente acesteia Top Previous Next Pentru a crea pagină tip LISTA DE LOCAȚII (CULTUR...",""],
["crearea_unei_pagini_noi.htm","Crearea unei pagini noi","Crearea unei pagini noi Top Previous Next Conținutul unui document se introduce în zona editabilă a CKEditor. În cazul în care doriți să generați ...",""],
["crearea_unei_pagini_simple.htm","Crearea unei pagini simple","Crearea unei pagini simple Top Previous Next Paginile simple, sau mai bine spus paginile de bază în cadrul sistemului de gestiune a conținutului (...",""],
["crearea_unor_pagini_cu_tabele_.htm","Crearea unor pagini cu tabele speciale","Crearea unor pagini cu tabele speciale Top Previous Next În cadrul platformei WebAPL sunt crete diverse instrumente complexe de editare a informaț...",""],
["dimensiunea_caracterelor.htm","Dimensiunea caracterelor","Dimensiunea caracterelor Top Previous Next În CKEditor dimensiunea caracterelor (SIZE) determină cât de mari sau mici vor fi afișate caracterele. ...",""],
["editare.htm","Editare","Editare Top Previous Next ENTER – finisează un paragraf și începe unul nou SHIF+ENTER – adaugă un sfârșit de linie (Line Breack) BACKSPACE, DEL – ...",""],
["editarea_unei_pagini_implicite.htm","Editarea unei pagini implicite (DEFAULT)","Editarea unei pagini implicite (DEFAULT) Top Previous Next Prin editarea unei pagini se înțelege acțiunea prin care datele introduse pe o pagină d...",""],
["formatarea_paragrafelor.htm","Formatarea paragrafelor","Formatarea paragrafelor Top Previous Next Formatarea paragrafelor sau stilizarea acestora este operațiune predefinită în CKEditor și se atribuie i...",""],
["ghilimelele_sau_citatele.htm","Ghilimelele sau citatele","Ghilimelele sau citatele Top Previous Next Sunt elemente de conținut care permit textului a se încadra în semele atribuite acestui element . Se re...",""],
["identarea_textului.htm","Identarea textului","Identarea textului Top Previous Next Identarea textului presupune plasarea unui anumit spațiul de la începutul blocului de elemente, aplicabile in...",""],
["imprimarea_unui_document.htm","Imprimarea unui document","Imprimarea unui document Top Previous Next CKEditorul permite a imprima documentul păstrând formatarea și conținutul acestuia. Documentul imprimat...",""],
["informaii_generale.htm","Informații generale","Informații generale Top Previous Next Back – end-ul este necesar pentru a rezolva problema de management și gestionare a conținutului, iar ca rezu...",""],
["inserarea_caracterelor_special.htm","Inserarea caracterelor speciale","Inserarea caracterelor speciale Top Previous Next Când scrieți, este de multe ori necesar a introduce caractere care nu sunt o parte a tastaturii ...",""],
["inserarea_de_emoticoane.htm","Inserarea de emoticoane","Inserarea de emoticoane Top Previous Next CKEditor este un editor online și nici un mediu on-line nu ar fi complet fără emoticoane (numite smileys...",""],
["inserarea_de_iframe.htm","Inserarea de iframe","Inserarea de iframe Top Previous Next CKEditor face posibilă pentru a insera Inline Frames la un document. Inline Frames, sau elemente iframe, vă ...",""],
["inserarea_imaginilor.htm","Inserarea imaginilor","Inserarea imaginilor Top Previous Next În scopul de a insera o imagine, se apasă butonul de pe bara de instrumente. Fereastra de proprietăți ale i...",""],
["inserarea_obiectelor_flash.htm","Inserarea obiectelor flash","Inserarea obiectelor flash Top Previous Next CKEditorul permite de a adăuga elemente ADOBE FLASH în document într-o manieră simplă și intuitivă do...",""],
["instalarea.htm","Instalarea","Instalarea Top Previous Next Platforma WebAPL a fost concepută ca un Sistem individual de Management al Conținutului înglobând în structura aceste...",""],
["limbile_de_comunicare_in_cms.htm","Limbile de comunicare în CMS","Limbile de comunicare în CMS Top Previous Next Limbile de comunicare a sistemului de administrare a conținutului sunt similare cu cele existente p...",""],
["linkuri__emailuri_i_ancore.htm","Linkuri, emailuri și ancore","Linkuri, emailuri și ancore Top Previous Next Opțiunile de inserare a linkurilor în CKEditor sunt opțiuni care oferă posibilitatea de a insera obi...",""],
["lucrul_cu_documentele.htm","Lucrul cu documentele","Lucrul cu documentele Top Previous Next ESC – închide o fereastră de dialog CKEditor, o listă drop-down sau un meniu contextual. De asemenea, se î...",""],
["lucrul_cu_pagina_modulul_acte_.htm","Lucrul cu pagina modulul acte locale","Lucrul cu pagina modulul acte locale Top Previous Next Modulul acte locale este unui destinat pentru a stoca toate actele emise de autoritatea pub...",""],
["lucrul_cu_tabelele.htm","Lucrul cu tabelele","Lucrul cu tabelele Top Previous Next Odată inserat în document, tabelul poate fi modificat. Pentru a edita tabelul, fie se face dublu-click pe el,...",""],
["lucru_cu_documentele.htm","Lucru cu documentele","Lucru cu documentele Top Previous Next Acest capitol este orientat spre a descrie modalitatea de lucru cu documentele în CKEditor. Conține de asem...",""],
["lucru_cu_pagina_contacte_i_con.htm","Lucru cu pagina contacte și contacte utile","Lucru cu pagina contacte și contacte utile Top Previous Next Pagina contacte este o pagină un pic mai deosebită decât alte pagini. În sensul dat, ...",""],
["mecanismul_de_autentificare_in.htm","Mecanismul de autentificare în Backend","Mecanismul de autentificare în Backend Top Previous Next Așa cum am menționat, CMS-ul este un instrument de gestiune a informațiilor plasate pe si...",""],
["meniul_acte_locale.htm","Meniul ACTE LOCALE","Meniul ACTE LOCALE Top Previous Next Meniul Acte Locale.md este un meniu care va stoca informațiile cu privire la actele locale emise de autoritat...",""],
["meniul_angajri.htm","Meniul ANGAJĂRI","Meniul ANGAJĂRI Top Previous Next Meniul Angajări este un meniu destinat colectării de CV-uri pentru eventualele posturi vacante existente în cadr...",""],
["meniul_buletin_informativ.htm","Meniul BULETIN INFORMATIV","Meniul BULETIN INFORMATIV Top Previous Next Meniul date este un meniu pur informativ de stocare a datelor despre vizitatori și doritorii de a se a...",""],
["meniul_calendar.htm","Meniul CALENDAR","Meniul CALENDAR Top Previous Next Este un meniu destinat pentru programarea diverselor evenimente ce urmează a avea loc și pentru care cetățenii t...",""],
["meniul_discut_on-line.htm","Meniul DISCUTĂ ON-LINE","Meniul DISCUTĂ ON-LINE Top Previous Next Platforma WebApl este dotată cu un instrument performat de comunicare cu cetățenii, și anume opțiunea de ...",""],
["meniul_extensii.htm","Meniul EXTENSII","Meniul EXTENSII Top Previous Next Sistemul CMS al platformei WebApl se prezintă a fi un sistem modular care permite a utiliza doar instrumentele s...",""],
["meniul_filemanager.htm","Meniul FILEMANAGER","Meniul FILEMANAGER Top Previous Next Meniul dat permite un acces mai rapid la sistemul de gestiune a tuturor fișierelor încărcate pe site sau ataș...",""],
["meniul_galerie.htm","Meniul GALERIE","Meniul GALERIE Top Previous Next Meniul Galerie este destinat pentru a crea galerii de fotografii ce pot fi utilizate pentru a fi plasate pe diver...",""],
["meniul_help.htm","Meniul HELP","Meniul HELP Top Previous Next Meniul Help este un meniul suplimentar care vine să ofere un instrument eficient de instruire în gestiunea site-ului...",""],
["meniul_limbi.htm","Meniul LIMBI","Meniul LIMBI Top Previous Next Limbile de comunicare a site-ului la nivel de utilizator sunt stabilite în sistemul de gestiune a conținutului în m...",""],
["meniul_loguri.htm","Meniul LOGURI","Meniul LOGURI Top Previous Next Este destinat utilizatorilor cu cunoștințe avansate și e orientat în special pe verificarea funcționalității site-...",""],
["meniul_orizontal.htm","Meniul orizontal","Meniul orizontal Top Previous Next Desigur, că acesta este un meniul plasat în partea de sus a CMS-ului și cuprinde următoarele elemente: Setări –...",""],
["meniul_pagini.htm","Meniul Pagini","Meniul Pagini Top Previous Next Este practic baza de construcție a întregului site funcțional și care cuprinde întreaga bază de date sistemului cr...",""],
["meniul_persoane.htm","Meniul PERSOANE","Meniul PERSOANE Top Previous Next Meniul Persoane este meniul destinat gestiunii tuturor persoanelor care sunt membrii ai aparatului administrativ...",""],
["meniul_petiii.htm","Meniul PETIȚII","Meniul PETIȚII Top Previous Next Meniul Petiții este destinat pentru stocarea plângerilor depuse pe site-ul APL creat. Formularul destinat acestei...",""],
["meniul_postri.htm","Meniul POSTĂRI","Meniul POSTĂRI Top Previous Next Meniul Grupe de postări este un alt Meniu de bază a site-ului care cuprinde, în general, informații ce se actuali...",""],
["meniul_setri.htm","Meniul SETĂRI","Meniul SETĂRI Top Previous Next Meniul orizontal SETĂRI este un meniu de bază al platformei și în general al site-urilor pe care aceasta le gestio...",""],
["meniul_sondaje.htm","Meniul SONDAJE","Meniul SONDAJE Top Previous Next Meniul Sondaje este un modul suplimentar creat și servește drept instrument pentru gestiunea sondajelor care pot ...",""],
["meniul_teme.htm","Meniul TEME","Meniul TEME Top Previous Next Este un modul destinat similar doar administratorilor site-urilor și poate fi utilizat și de dezvoltatori pentru a î...",""],
["meniul_utilizatori.htm","Meniul UTILIZATORI","Meniul UTILIZATORI Top Previous Next Adăugarea/Editarea/Ștergerea utilizatorilor Utilizatorii în cadrul sistemului CMS pot fi adăugați DOAR de uti...",""],
["meniul_variabile.htm","Meniul VARIABILE","Meniul VARIABILE Top Previous Next Meniul Variabile este un meniu de ordin tehnic care vine să susțină funcționalitatea site-ului și a tuturor ele...",""],
["meniul_vertical.htm","Meniul Vertical","Meniul Vertical Top Previous Next Meniul vertical este de fapt și meniul de bază care gestionează întregul conținut a site-ului. În vederea elabor...",""],
["navigarea.htm","Navigarea","Navigarea Top Previous Next HOME – revine la începutul liniei CTRL + Home – revine la începutul documentului END – transferă la finele liniei CTRL...",""],
["navigarea_in_baza_listei_barel.htm","Navigarea în baza listei barelor de instrumente","Navigarea în baza listei barelor de instrumente Top Previous Next TASTA ÎN JOS, ENTER și SPACE Deschide lista verticală după ce este selectat pe b...",""],
["navigarea_in_cadrul_ferestrelo.htm","Navigarea în cadrul ferestrelor de dialog","Navigarea în cadrul ferestrelor de dialog Top Previous Next TAB ȘI SHIFT + TAB Când fereastra de dialog nu este focusată, combinația de taste indi...",""],
["navigarea_in_cadrul_meniurilor.htm","Navigarea în cadrul meniurilor contextuale","Navigarea în cadrul meniurilor contextuale Top Previous Next TAB, SHIFT+TAB Când meniul contextual este deschis, apăsați pe Tab pentru a trece pri...",""],
["navigarea_in_ferestrele_de_cul.htm","Navigarea în ferestrele de culori","Navigarea în ferestrele de culori Top Previous Next TASTA ÎN JOS, ENTER și SPACE Va deschide fereastra de culori îndată ce aceasta va fi selectată...",""],
["navigarea_pe_bara_de_instrumen.htm","Navigarea pe bara de instrumente","Navigarea pe bara de instrumente Top Previous Next Odată ce sunteți focalizați pe bara de instrumente și apăsați Alt + F10, Tab și Shift + Tab va ...",""],
["navigarea_util.htm","Navigarea utilă","Navigarea utilă Top Previous Next CKEditor este compatibil cu mai multe standarde de accesibilitate, inclusiv conținutul Web Accessibility Guideli...",""],
["navigare_de_baz.htm","Navigare de bază","Navigare de bază Top Previous Next Tasta TAB și combinația și SHIFT + TAB Vă permit să vă mișcați în și din editor de la un element la altul. Pent...",""],
["pagina_principal.htm","Pagina principală","Pagina principală Top Previous Next Template (Șablon) 1 Pagina PRINCIPALĂ (Home Page) a site-ului pentru prima versiune de desing (Numită în pe pl...",""],
["paginile_interioare.htm","Paginile interioare","Paginile interioare Top Previous Next Ca structură generală, arborele de conținut a site-ului este prezentat în ANEXA nr. 1 Arborele de conținut e...",""],
["personaliti_marcante.htm","Personalități marcante","Personalități marcante Top Previous Next Pagina personalități marcante este o pagină asemănătoare cu viceprimarii, iar pentru a creao asemenea pag...",""],
["plasarea_anunurilor_de_achizii.htm","Plasarea anunțurilor de achiziții publice","Plasarea anunțurilor de achiziții publice Top Previous Next Pagina de achiziții publice este o altă pagină asemănătoare cu paginile de noutăți și ...",""],
["primar.htm","Primar","Primar Top Previous Next Platforma WebAPL permite a crea mai multe tipuri de pagini pe care se plasează persoane, fie cu o descriere mai detaliată...",""],
["referine_utile__butoane.htm","Referințe utile – butoane","Referințe utile – butoane Top Previous Next În cadrul editorului de texte CKEDITOR se întâlnesc următoarele butoane – instrumente BUTONUL / INSTRU...",""],
["rezumat.htm","Rezumat","Rezumat Top Next Prezentul document reprezintă documentația tehnică și de utilizare a platformei de gestionare a conținutului (CMS) WebAPL 1.0 , d...",""],
["secretar_consiliul_local.htm","Secretar consiliul local","Secretar consiliul local Top Previous Next Ca esență, pagina Secretar Consiliul Local se creează similar paginii primar sau viceprimar, doar că ac...",""],
["selectarea_abloanelor_i_aspect.htm","Selectarea șabloanelor și aspectul acestora","Selectarea șabloanelor și aspectul acestora Top Previous Next Un șablon de conținut este o caracteristică CKEditor care permite de a controla stru...",""],
["selectarea_textului.htm","Selectarea textului","Selectarea textului Top Previous Next Când doriți să aplicați o acțiune de formatare a unei porțiuni mai scurte sau mai lungi de text, aveți posib...",""],
["selectarea_textului2.htm","Selectarea textului","Selectarea textului Top Previous Next CTRL+A – selectează conținutul întregului document SHIFT+SĂGEATĂ – selectează câte un fragment literă cu lit...",""],
["stilizarea_textului.htm","Stilizarea textului","Stilizarea textului Top Previous Next Stilizarea textului reflectă modalitatea cum textul va fi afișat în document, respectiv pe interfața site-ul...",""],
["stilizarea_textului2.htm","Stilizarea textului","Stilizarea textului Top Previous Next CTRL+B – atribuie îngroșarea la text CTRL+I - atribuie înclinarea la text CTRL+U - atribuie sublinierea la t...",""],
["stiluri_predefinite.htm","Stiluri predefinite","Stiluri predefinite Top Previous Next Stilurile predefinite de formatări în cadrul CKEditor sunt utilizate pentru a atribui nuanțe stilistice în m...",""],
["structura_cms-ului.htm","Structura CMS-ULUI","Structura CMS-ULUI Top Previous Next CMS-ul site-urilor platformei WebAPL este constituit din 4 componente principale: 1. Meniul orizontal 2. Meni...",""],
["structura_interfeei_de_lucru_a.htm","Structura interfeței de lucru a editorului de text CKEDITOR","Structura interfeței de lucru a editorului de text CKEDITOR Top Previous Next Structura elementului CKEditor este compusă din următoarele zone: 1....",""],
["structura_site-urilor_apl_fron.htm","Structura site-urilor APL (Frontend)","Structura site-urilor APL (Frontend) Top Previous Next Orice site elaborat în baza WebAPL și care poate fi gestionat privitor la plasarea conținut...",""],
["suprascriere_i_subscriere.htm","Suprascriere și subscriere","Suprascriere și subscriere Top Previous Next Pe lângă opțiunile standarde de formatare, în CKEditor se pot executa diverse opțiuni de supra sau su...",""],
["sursa_documentelor.htm","Sursa documentelor","Sursa documentelor Top Previous Next CKEditorul este un editor on-line car produce un cod curat, conform standardelor HTML în vigoare. Aceasta sem...",""],
["taie__copie__alipete.htm","Taie &#38; Copie &#38; Alipește","Taie &#38; Copie &#38; Alipește Top Previous Next CTRL+X, SHIFT+DEL – taiere, echivalent la CUT CTRL+C - copiere, echivalent la COPY CTRL+V, SHIFT+INSERT ...",""],
["terge_formatarea.htm","Șterge formatarea","Șterge formatarea Top Previous Next CKEditorul oferă posibilitatea nu doar de a executa formatări diferențiate a conținutului textual din zona de ...",""],
["tierea__copierea_i_alipirea.htm","Tăierea, copierea și alipirea","Tăierea, copierea și alipirea Top Previous Next Printre cele mai utilizate acțiuni în CKEditor sunt acțiunile de TĂIERE, COPIERE ȘI ALIPIRE (CUT, ...",""],
["tip_de_pagini_i_caracteristici.htm","Tip de pagini și caracteristicile acestora","Tip de pagini și caracteristicile acestora Top Previous Next Paginile care pot fi create în cadrul platformei WebAPL și gestionate de sistemul de ...",""],
["viceprimar.htm","Viceprimar","Viceprimar Top Previous Next Ca esență, pagina viceprimar se creează similar paginii primar, doar că acestea se atribuie la o nouă grupă de persoa...",""],
["vizualizarea_documentului.htm","Vizualizarea documentului","Vizualizarea documentului Top Previous Next CKEditorul este un editor WYSIWYG care indică că conținutul creat arat similar pe cât posibil cu rezul...",""]];
